services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: osteo_insight
    environment:
      - APP_ENV=production
    restart: unless-stopped
    networks:
      - main_network

networks:
  main_network:
    external: true